version: "3.7"
services:

  api.andkra.eu:
    build:
      context: ./envoy/
      dockerfile: DOCKERFILE
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
  chathub:
    build:
      context: .
      dockerfile: Dockerfile-hub
    volumes:
      - ./hub-envoy.yaml:/etc/hub-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - chathub
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
networks:
  envoymesh: {}